language: node_js
node_js:
  - '8'
  - '6'
script:
  - npm run test
  - npm run build
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master
after_success: npm run coverage
